#!/bin/sh 

set -e 

. ./build-api

#export GOPATH=${PWD}
export GOBIN=${PWD}/bin

SERVER_PATH="bin/server"
CLIENT_PATH="bin/client"

eval $(go env)

go install github.com/coreos/shortbread/cmd/shortbreadctl

go build -o ${SERVER_PATH} server/server.go
go build -o ${CLIENT_PATH} client/client.go
