#!/bin/sh 

set -e 

. ./build-api

#export GOPATH=${PWD}
export GOBIN=${PWD}/bin

SERVER_PATH="bin/server"
#CLI_PATH="bin/shortbreadctl"

eval $(go env)

#go install github.com/coreos/shortbread
go install github.com/coreos/shortbread/cmd/shortbreadctl

go build -o ${SERVER_PATH} server/server.go
#go build -o ${CLI_PATH} cmd/shortbreadctl.go


