#!/bin/sh 

set -e 
GEN_PATH="bin/google-api-go-generator"

if [ ! -f ${GEN_PATH} ]; then 
  go build -o ${GEN_PATH} github.com/coreos/shortbread/Godeps/_workspace/src/code.google.com/p/google-api-go-client/google-api-go-generator
fi

./bin/google-api-go-generator \
     -googleapi_pkg "github.com/coreos/shortbread/Godeps/_workspace/src/code.google.com/p/google-api-go-client/googleapi" \
     -api_json_file "api/api.json" \
     -output "api/shortbreadapi.go"
